### ISSUE TITLE
Renderers (other than TSV) disappear, when 'subtotals = FALSE' AND 'tsv = TRUE'

### ISSUE THREAD

**Issue by ghost** [fraupflaume/rpivotTable#4] opened 2022-11-02 08:13 UTC
```
    rpivotTable(mtcars, rows = "am", cols = "cyl", width = "90%", height = "40%", subtotals = FALSE, tsv = FALSE)  # OK
    rpivotTable(mtcars, rows = "am", cols = "cyl", width = "90%", height = "40%", subtotals = TRUE, tsv = TRUE)    # OK
    rpivotTable(mtcars, rows = "am", cols = "cyl", width = "90%", height = "40%", subtotals = TRUE, tsv = FALSE)   # OK
    rpivotTable(mtcars, rows = "am", cols = "cyl", width = "90%", height = "40%", subtotals = FALSE, tsv = TRUE)   # NOT OK!
```

**Expected behavior**
In the 4th case, the list of available renderers should be like this. 

![image](https://user-images.githubusercontent.com/3167917/199432121-03d0f8bd-b494-4849-b7e0-6a0e4914cfe5.png)

Instead, only "TSV Export" is shown as available.
![image](https://user-images.githubusercontent.com/3167917/199432900-58f77446-054b-4d96-9b38-66d931db308c.png)

I'm hoping it's just a minor fix.

**Comment by mink-lge** [comment] 2022-11-02 16:42
In `rpivottable.js` I attempted the following modifications, and they appear to be working.

```
      if(x.tsv && x.subtotals) { // put tsv first so other renderers have priority 
        x.params.renderers = $.extend($.pivotUtilities.export_renderers, // $.pivotUtilities.renderers, 
                                      x.params.renderers);
      } else if (x.tsv && !x.subtotals) {
          x.params.renderers = $.extend($.pivotUtilities.export_renderers, 
                  $.pivotUtilities.renderers,
                  $.pivotUtilities.d3_renderers,
                  $.pivotUtilities.c3_renderers);
      	}
```
Also, when I tried to include the `$.pivotUtilities.renderers` in the second line, I got all the renderers! Do you remember [this ](https://github.com/fraupflaume/rpivotTable/discussions/2#discussioncomment-2728907)discussion?

Anyway, these are merely quick tests. Find out for yourself what the ideal solution is.

**Comment by mink-lge** [comment] 2022-11-12 09:08
Okay, since the aforementioned issue is being addressed in some way, I'll use this chance to ask about a more difficult issue for which I haven't been able to come up with a solution.

When I tried to switch from R 4.1.2 to 4.2.1 my rmarkdown reports (all encoded in UTF-8) don't work because queries containing Greek characters are not sent correctly to the database (a Sybase ASE 15, with CP1253 encoding). 

The problem is not related to RStudio because I tried to `rmarkdown::render` the .rmd file from RGUI as well. The report is generated correctly by the 4.1.2 RGUI but fails by the 4.2.1 one.  

Unfortunately I can't make a reproducible example of this problem, so I can post a S.O. question about it. Also, I failed to find anything useful by googling.  

Oh! One additional problem that occurred: Within the rmd reports, I often `source` a file of type .r (which contains generic functions and also contains another query with Greek characters). Up to version 4.1.2, in order for files like this (*.r) to work correctly, they had to be saved with native encoding (CP1253). (At least that was the conclusion I had come to). With R 4.2.1 they are not even read correctly via `source`.

As you understand, I'm simply not even considering switching to 4.2.# under these circumstances.

I apologize if I bored you. I would greatly appreciate any ideas you may have.

**Comment by fraupflaume** [comment] 2022-11-12 21:44
I've pushed the updates to `rpivotTable.js` so that's fixed. Sorry about that.

BLUF or TL;DR;

As far as the Greek, RStudio, and R... I've been playing around with this a little bit. I haven't gone so far as to create an arbitrary database, but I did play around with RMD inline Greek, Greek strings, and importing Greek from a source file. 

I'm not having these issues. So, my first question is whether or not I've truly replicated any of the things that are causing problems on your end.

If I have, I'm not sure if this is an encoding issue, a Windows issue, or if there is something else going on. I can tell you that the launch of 4.2 was supposed to fix some very long-awaited issues between base R and UTF-8—specifically to address issues regarding language encoding (languages of people, not programming).

### And all the rest...

My current versions:

|What            |Version            |
|------------|---------------|
|OS      |x86_64-apple-darwin17.0 (latest Mac OS)|
|R         |4.2.1|
|RStudio |2022.07.2+576 "Spotted Wakerobin"|
|R Markdown |2.18|
|knitr|1.40|

I created two small script files with the exact same content. I saved one with CP1253 encoding. I saved the other with ISO8859-7 encoding. I don't know exactly what type of content you have, so I just used Greek strings in a data frame and in a graph. Here's the code I used:

```
library(tidyverse)

# create a data frame
x <- c("Κόκκινο", "Κίτρινο"," Πράσινο")
y <- c(5,4,9)
df <- data.frame(x, y)

ggplot(df, aes(x, y)) + geom_point()
``` 
When I source the file, it renders correctly (both encodings).

![image](https://user-images.githubusercontent.com/32872512/201492386-fb9d10a3-0423-41f1-ab2a-6afa342c3f25.png)

After closing and reopening it RStudio, all I see is '?' in place of the Greek letters. However, when I sourced it in RMD (RMD is NOT encoded in anything other than UTF-8), It rendered as I had expected. (By the way, I have no idea what those words mean...I copied it from the net.) I initially encoded the RMD as Greek, but nothing worked. 

Here's what I've got in the RMD. 

````
---
title: "Untitled"
author: "me"
date: "2022-11-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
# knitr::read_chunk("grkScript.R")
# Sys.setlocale("LC_CTYPE", "en_US.UTF-8")
library(tidyverse)  # here so that it doesn't echo when source is called
library(gridExtra)
library(rpivotTable)

data(mtcars)
```

<!--- Multi-language web safe font ---->

```{r, engine="js",results="asis"}
$('head').append('<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Noto+Sans&family=Noto+Sans+Mono&family=Noto+Serif&display=swap" rel="stylesheet">')
```

<style>
p {
  font-family: 'Noto Sans', sans-serif;
}
.main-container {
  max-width: 90vw;
  margin: unset;
}
pre > code {
  font-family: 'Noto Sans Mono', monospace;
}
</style>

```{r getter, fig.show="hold", fig.align="center", out.width="100%", fig.height=2}

this <- source("grkScript.R", encoding = "ISO8859-7")

that <- source("grkScript2.R", encoding = "CP1253")
# show the plots
grid.arrange(this[[1]], that[[1]], nrow = 1)
```

Όλα αυτά είναι ωραία και κομψά. Δεν ξέρω καθόλου ελληνικά, οπότε χρησιμοποιώ το Google Translate.

```{r sigh}

tellMe <- " Όλα αυτά είναι ωραία και κομψά. Δεν ξέρω καθόλου ελληνικά, οπότε χρησιμοποιώ το Google Translate."

tellMe

```
````

![image](https://user-images.githubusercontent.com/32872512/201495711-10b35514-2fb6-4bd8-a332-4f9772783757.png)

**Comment by mink-lge** [comment] 2022-11-13 07:35
_Another invitation ?!? (Thanks for making me laugh. I needed it. Why did you have to be so nice?)
You know, I really hope I didn't have to even open Rstudio again, much less deal with a language I don't know. (Speaking of languages, learning German right now is what I find most fascinating.)
All you might need is a better way to be notified of new messages._ 😁

--- 

On the laptop I have at home (R 4.2.1), the behavior is as you describe. No problem. Perhaps the issue is limited in the database communication. I'll do some more careful testing at work, starting Monday, and I will post here my findings (if you can think of a better location, please let me know).

Herzlichen Dank.

**Comment by mink-lge** [comment] 2022-11-13 16:08
I think you have already solved the `source` problem. I wasn't passing the `encoding` argument to the source command 🤦‍♂️. As a result it used the `native.enc`, which is `Greek_Greece.utf8` (and, in R 4.1.# was `Greek_Greece.1253`). 
_Sheesh! I know that the time has come to give up programming. I am close, I swear._

**Comment by fraupflaume** [comment] 2022-11-14 00:19
I pretty much learned German from my grandparents speaking it around me. I studied Russian for years in college. With no one to use it with and no when to correct it when I screw up...yea, I don't remember any of it now.

I have a question...so in English (and probably in many other languages) we primarily use Greek letters for specific elements in math, like $\theta$ for angles or $\Delta$ for the difference or change. What do Greeks use? I feel like it just wouldn't have the same significance. (Like how it just sticks out in English.)

As far as messages...ya, I kind of suck at that. It's not just messages. Really, it's communication in general. I'm a work in progress...for like my entire life.

I think it's fine to put your server/encoding content here. I doubt all that many people are looking at this repo!

By the way, (you may already know this) I read that CP1253 violates a few issues with encoding, which is why ISO8859-7 differs. I'm not sure how big of a deal it is. I just thought I would mention it.

I downloaded a trial of SAP ASE to see if I could help....the first hurdle—it doesn't run on Mac; I use Virtual Box for cybersecurity reasons with several different Linux OS. I don't have one with Windows, though. It's been a rather frustrating journey so far! When I finally got the server running I couldn't interact with it (operator error). I've finally got it running...my next hurdle... I need a Greek-encoded database. I'm working on translating one of the example databases. I'm having all sorts of fun trying to regex the strings out of the bash file that creates that example database. The Greek will probably be laughably poor grammar, but meh, it'll at least get me to the point where I might be able to reproduce some of the issues you're having.

**Comment by mink-lge** [comment] 2022-11-14 09:24
Greeks simply use the same mathematical symbols as in most countries. Those symbols are a little more familiar to us, but they nevertheless differ from the other symbols in the same way.

The truth is that your communication issue can lead to mistranslations like: "No response _**is**_ a response", especially if one has a good reason to worry about this. If I continue to have the pleasure of communicating with you, I shall begin speaking to you in German in a short time 😊

I also have a couple of questions. 

1. I noticed that you didn't add `pivotUtilities.renderers` in `if(x.subtotals)`. Was there a problem, or did you not like the idea of having all the renderers available?
2. How can you find out that the encoding of a file is, say "ISO8859-7" (as in "grkScript.R") if you dont't know it?

I don't think you need to go to that much trouble (database installations). Something has changed in the way the query is sent to the database. I wonder if it is a problem with the `odbc` package. In the meantime I found [this ](https://github.com/r-dbi/odbc/issues/67)related issue. The last comments are relatively recent. [This ](https://github.com/r-dbi/odbc/issues/67#issuecomment-1100246993) one worked for me, but in reverse. Here is an example of how I had to use `iconv` in order to get the correct results.

```
crs.odbc <- dbConnect(odbc::odbc(), "PIND_64", encoding = "CP1253")

dbGetQuery(crs.odbc, iconv("
  select *
  from my_tbl
  where ta_type in ('Άνω Διάβαση Οδού','Οδική Γέφυρα')
","CP1253", "UTF-8"))
```
But even if I were willing to convert all my queries this way (which I'm not), I would still have the unsolved problem of queries inside ```{sql}  ``` chunks, for which I have found no way to send them correctly.

You might find the output below useful.
R 4.1.2
``` r
l10n_info()
#> $MBCS
#> [1] FALSE
#> 
#> $`UTF-8`
#> [1] FALSE
#> 
#> $`Latin-1`
#> [1] FALSE
#> 
#> $codepage
#> [1] 1253
#> 
#> $system.codepage
#> [1] 1253
```


R 4.2.2
``` r
l10n_info()
#> $MBCS
#> [1] TRUE
#> 
#> $`UTF-8`
#> [1] TRUE
#> 
#> $`Latin-1`
#> [1] FALSE
#> 
#> $codepage
#> [1] 65001
#> 
#> $system.codepage
#> [1] 65001
```

**Comment by fraupflaume** [comment] 2022-11-14 19:37
Klingt nach einer tollen Idee, schreib auf Deutsch!

1)--- Warum nicht? When I tested it with`$.pivotUtilities.renderers` attached to  `if(subtotals)`, `rpivotTable` will not render if `subtotal = T`. Were you able to get a different outcome? (Am I missing something!!!????!)

2) I used Google. However, I can say that there are many resources out there, but some aren't great. [This one works well](https://www.science.co.il/language/Character-sets.php), but you have to know to add "CP" to the Windows codes.

As far as the incomprehensible strings--- can you tell me if, without knitting or rendering, you just printed the data frame (or whatever structure) to the console, does it render correctly? Is it just _on the graph_ that reflects nonsense?

If it's nonsense regardless, have you tried using `stringi::stri_encode` instead of `iconv`? Also, it may pay to try leaving the encoding off in `dbConnect`. Right now it looks as if you're trying to change the encoding 2 times... Since you've been at this for a while, my ideas may be 'been there-done that.' 

`gt` is a pretty snazzy package! I haven't seen that resource before. It's on the list 'useful' now.

**Comment by mink-lge** [comment] 2022-11-15 05:10
Ich mag Geheimnisse aber nicht so sehr...
(This post is for pivottable only. I will post later for the rest)
If it doesn't work for you, you did well to skip it !

![image](https://user-images.githubusercontent.com/107258922/201830111-6d147a5c-27d3-434f-bdbb-880b92f26b36.png)

![image](https://user-images.githubusercontent.com/107258922/201831442-2c9cc9e3-14f1-40c6-aba6-2b841f4ed96e.png)

**Comment by mink-lge** [comment] 2022-11-15 07:15
### On the SQL Server rmd report case.

The data.frame does NOT print correctly to the console. (I see the same characters as in the plot).
If I omit the `encoding = "CP1253"` from `dbConnect`, the strings are _seem_ to be correct indeed, but they aren't (check lines 5 and 27 in "nodes")

(I attach three pairs of "links" and "nodes" files, one for each case). 

1. SQL_Server_sankey_1.zip: R 4.1.2, (connection with encoding ON in dbConnect).
2. SQL_Server_sankey_2.zip: R 4.2.2, (connection with encoding ON in dbConnect).
3. SQL_Server_sankey_3.zip: R 4.2.2, (connection with encoding OFF in dbConnect).

```
library(networkD3)
sankeyNetwork(
  Links = links, Nodes = nodes, Source = "source",
  Target = "target", Value = "value", NodeID = "name",
  units = "k€", fontSize = 10, fontFamily = "Arial Narrow", 
  nodeWidth = 30, LinkGroup = "col", NodeGroup = NULL, 
  margin = list(left = 220, right = 0), iterations = 256,
  colourScale = JS("d3.scaleOrdinal(d3.schemeCategory20c);")
)
```
That's the error in case 3.
```
Error in gsub("</", "\\u003c/", payload, fixed = TRUE) : 
  input string 1 is invalid UTF-8
```

[SQL_Server_sankey_2.zip](https://github.com/fraupflaume/rpivotTable/files/10010101/SQL_Server_sankey_2.zip)
[SQL_Server_sankey_1.zip](https://github.com/fraupflaume/rpivotTable/files/10010102/SQL_Server_sankey_1.zip)
[SQL_Server_sankey_3.zip](https://github.com/fraupflaume/rpivotTable/files/10010103/SQL_Server_sankey_3.zip)

**Comment by fraupflaume** [comment] 2022-11-15 18:20
In response to the first post you made:

I went back to look and see if it was something like an operator error, something that was dependent on the order I listed the utilities, or any other reason that it worked for you and not me. I found nothing different...but something is DEFINITELY different because it worked without an issue. Sigh. I'll chalk it up to operator error. I've updated the `rpivotTable` package again! 

I'm not sure what you meant in your German statement...secrets? I'm confused! Tut mir leid! Erklär?

Völlig off-topic: Ich dachte nur, ich erwähne mal mein deutsches Lieblingswort. Ich finde es einfach lächerlich lang: Geschwindigkeitsbegrenzung. Es wird häufiger als Tempolimit bezeichnet.

I must have been pretty young, definitely under the age of 10, when I learned the endearment sweetie in German. It was more along the lines of someone said it and I asked what it meant. So some time later (same day? same week? months later?? I don't know), I wanted to use it when speaking to my sister. Only I said it wrong... 
So, the word that was said for sweetie was a derivation of Schatz (treasure), like Schatzie.
What I said was Schwanzie... stick that in a translator (I'm not referring to a tail, either)...I know there was TON of laughing. Now that I'm much older I use it with my sister as an inside joke. At the time, I think they told me I was saying pig or piggy (that's Schwein...not Schwanz!). I was just a little girl. I'm glad they spared me the utter mortification had I really know what I said!

**Comment by ghost** [comment] 2022-11-15 18:46
My statement was supposed to mean: I like mysteries but not that much. Because of all these strange things that happen with the software we use.

My favorite word is küssen. I think the use of umlaut here fits perfectly with the action the word describes.


I am only in my 4th month of taking German and I have a lot of questions. You don't want me to start asking you about them too. :)

Anyway, just once. Mal is a very common word but in some cases I don't know how to translate it. What does it mean in the sentence you used it in?

**Comment by fraupflaume** [comment] 2022-11-15 21:08
I'm actually trying to work through all of the interesting things you've given me! (Encoding & all that...)

However, I just noticed this and wanted to respond to what you wrote most recently. (I'm still coming back to all the rest!)
The word mal can go just about anywhere (like _just_ in this sentence). You can always narrow down what it means a bit by whether its capitalized. It can be a noun or an adverb. All nouns are capitalized in German.

I'm sure you're aware of the literal meaning - once, or one time, times, something along those lines. However, it's used for emphasis in what I wrote. _I just want to tell you my favorite word._ or _I just thought I'd just tell you what my favorite word is._ Really though, because of _Ich dachte nur_ I really just doesn't sound right with out _mal_. It is still grammatically correct if I write _Ich dachte nur, ich erwähne mein deutsches Lieblingswort_, though. (You don't need _mal_...well, ever.)

Thinking back, I think my Oma used the word _doch_ in every other sentence. _Doch_ is another word that doesn't really mean anything most of the time (just like _really_ in this sentence).

**Comment by ghost** [comment] 2022-11-16 08:48
What a fantastic teacher you are!

> Ach und könnte ich **_doch_** nur ein einziges **_Mal_** die Uhren rückwärts drehen...

 [This song](https://music.youtube.com/watch?v=rbk9oCwqAsQ) has long been a favorite of mine. I like it a lot more now that I can figure out the lyrics. 

Here is another small gift for you. This is the website for “[Advanced R Solutions](https://advanced-r-solutions.rbind.io/index.html)” which provides solutions to the exercises from Hadley Wickham’s [Advanced R](https://adv-r.hadley.nz/), **_2nd edition_**.

**Comment by fraupflaume** [comment] 2022-11-16 17:59
I have found no method that will tell me unequivocally what the encoding is for a file. It seems like no matter what it wants to tell me whatever my native encoding is—so annoying!

Alright, I spent a while looking at the Sankey Rdata files. I'm sure I see something different than what you see because of the local set for R/Rstudio.

That being said, I'm not sure what's different about the 3rd zip file's 5th node. I can tell you that this is the 5th observation of each of the Rdata files' nodes (while my local is still "en"):

"Συστ. ΣΗΜ/ΣΗΣ-ΤΗΛ/ΣΗΣ & ETCS (Εγκ.,Λειτ.,Συντ.): Αθη-Θεσ (εκτος Λιαν-Δομ),\xce"
"Συστ. ΣΗΜ/ΣΗΣ-ΤΗΛ/ΣΗΣ & ETCS (Εγκ.,Λειτ.,Συντ.): Αθη-Θεσ (εκτος Λιαν-Δομ),Θεσ-Πολυκ,Θεσ-Προμ"
"Ξ£Ο…ΟƒΟ„. Ξ£Ξ—Ξ\u009c/Ξ£Ξ—Ξ£-Ξ¤Ξ—Ξ›/Ξ£Ξ—Ξ£ & ETCS (Ξ•Ξ³ΞΊ.,Ξ›ΞµΞΉΟ„.,Ξ£Ο…Ξ½Ο„.): Ξ‘ΞΈΞ·-Ξ\u0098ΞµΟƒ (ΞµΞΊΟ„ΞΏΟ‚ Ξ›ΞΉΞ±Ξ½-Ξ”ΞΏΞΌ),Ξ"

What a hot mess! I thought this brought about an interesting way of determining the encoding of a file (although, obviously I have a good guess already). What happened is that it assumed the encoding is already UTF-8.

I can't take the third line and use either `iconv` or `stri_encode` or any other function because there is a mishmash of encoding in this single string. I have to break it down into bytes. I could use this extraction call to break strings down. That's assuming no data was lost when this was brought in. Are the three lines supposed to be identical?

`str_extract_all(notRight, "Ξ.(?=[^\\\\])|Ξ.$|Ξ\\\\u....|Ο.")[[1]]`

Since all through RData files had `links` and `nodes`, I numbered them like `nodes0`. I used this to rebuild that nodes that were shown like that third line:

```
library(tidyverse)
fixer <- function(notRight) {
  wrong <- str_extract_all(notRight, "Ξ.(?=[^\\\\])|Ξ.$|Ξ\\\\u....|Ο.")[[1]]
  fixed <- data.frame(original = wrong) %>% 
    mutate(correct = ifelse(!is.na(iconv(original, from = "UTF-8", to = "CP1253")),
                            iconv(original, from = "UTF-8", to = "CP1253"),
                            ifelse(!is.na(iconv(original, from = "UTF-8", to = "ISO-8859-7")),
                                   iconv(original, from = "UTF-8", to = "ISO-8859-7"),
                                   NA)))
  right <- reduce2(fixed$original, fixed$correct, .init = notRight, str_replace_all)
  print(right)
} 

nodes3 <- data.frame(name = invisible(lapply(1:length(nodes2$name), 
                                             function(j) fixer(nodes2$name[j]))) %>% 
                       unlist(use.names = F))
```

This is what I've got for line 5 now. I'm pretty sure something was dropped, because I'm guessing this line should end with that letter. I noticed that for a few other lines, as well (i.e., 'ΘεσσαλονίκΞ', which should have $\eta$ at the end instead, right? If so, then some data was lost. This encoding error should have "Ξ®" that would turn into $\eta$ when properly encoded.

"Συστ. ΣΗΜ/ΣΗΣ-ΤΗΛ/ΣΗΣ & ETCS (Εγκ.,Λειτ.,Συντ.): Αθη-Θεσ (εκτος Λιαν-Δομ),Ξ"

I did find that `iconv` was far more successful far more often than any other encoding function I used when I was messing around with this content. 

I ended up building a frame of reference for this, but I didn't actually use it. You might be able to use it if things are particularly ugly (in terms of encoding discovery).

```
library(rvest)
html <- read_html("https://www.key-shortcut.com/en/writing-systems/abg-greek-alphabet")
thatsIt <- html %>% html_nodes("table") %>% html_table()

Gr <- thatsIt[[3]]
Grel <- thatsIt[[4]]
gr_el <- data.frame(Unicode = c(unlist(Gr, use.names = F),
                             unlist(Grel, use.names = F))) %>% 
  mutate(uni = substring(Unicode, 1, 6),
         letter = substring(Unicode, 7, 7),
         description = substring(Unicode, 8)) %>% 
  separate(description, sep = "HTML", into = c("description", "decimal", "hex")) %>% 
  mutate(decimal = str_extract(decimal, "[0-9]+"),
         hex = substring(stri_reverse(hex), 2, 6) %>% stri_reverse()) %>% 
  select(-Unicode)

filter(gr_el, description == "")
gr_el[gr_el$uni == "U+1F1C", "description"] <- "GREEK CAPITAL LETTER EPSILON WITH PSILI AND OXIA"
gr_el[gr_el$uni == "U+1F1D", "description"] <- "GREEK CAPITAL LETTER EPSILON WITH DASIA AND OXIA"

gr_el$ISOtoUTF8 <- iconv(gr_el$letter, from = "ISO-8859-7", to = "UTF-8")
gr_el$CPtoUTF8 <- iconv(gr_el$letter, from = "CP1253", to = "UTF-8")
gr_el <- gr_el %>% filter(!str_detect(description, "COPTIC"))

comment(gr_el) <- paste0("The column `ISOtoUTF8` is what the letter looks like if the ",
                         "encoding was converted from ISO-8859-7 to UTF-8. ",
                         "The column `CPtoUTF8` is what the letter looks like if the the ",
                         "encoding was converted from CP1253 to UTF-8.")
```

I also wrote a function that tests two strings, like what encoding took "Μ" and gave me "Ξ\u009c".  

I went back to what I wrote that mentioned _nach_. I keep looking at it. It doesn't really translate correctly in English. You could say _Das klingt wie eine tolle idee._ For English, that translation is more understandable.

**Comment by ghost** [comment] 2022-11-16 18:22
Thank you very much for the effort you have put in. I admit that (at least at the moment) I'm having a hard time following what you're doing and I don't know which question to answer first (If something really needs to be answered and the questions are not rhetorical). 

What I suspect is that R (after the upgrade) misdiagnoses the encoding and either does a conversion (when it doesn't need to), or it doesn't (while it needs to). But, this appears to be too critical to not have been diagnosed (and corrected). I don't know what to assume.

This is the match that applies to me:

- SQL_Server_sankey_1.zip: R 4.1.2, (connection with encoding ON in dbConnect) 
Συστ. ΣΗΜ/ΣΗΣ-ΤΗΛ/ΣΗΣ & ETCS (Εγκ.,Λειτ.,Συντ.): Αθη-Θεσ (εκτος Λιαν-Δομ),Θεσ-Πολυκ,Θεσ-Προμ


- SQL_Server_sankey_2.zip: R 4.2.2, (connection with encoding ON in dbConnect):
Ξ£Ο…ΟƒΟ„. Ξ£Ξ—Ξ\u009c/Ξ£Ξ—Ξ£-Ξ¤Ξ—Ξ›/Ξ£Ξ—Ξ£ & ETCS (Ξ•Ξ³ΞΊ.,Ξ›ΞµΞΉΟ„.,Ξ£Ο…Ξ½Ο„.): Ξ‘ΞΈΞ·-Ξ\u0098ΞµΟƒ (ΞµΞΊΟ„ΞΏΟ‚ Ξ›ΞΉΞ±Ξ½-Ξ”ΞΏΞΌ),Ξ


- SQL_Server_sankey_3.zip: R 4.2.2, (connection with encoding OFF in dbConnect):
Συστ. ΣΗΜ/ΣΗΣ-ΤΗΛ/ΣΗΣ & ETCS (Εγκ.,Λειτ.,Συντ.): Αθη-Θεσ (εκτος Λιαν-Δομ),\xce

The first one is the correct string. In the other two cases the last part of the string, i.e. "Θεσ-Πολυκ,Θεσ-Προμ", is lost. And that "\xce", in the 3rd case, causes the program to crash. 

P.S. I have just read about [this new book](https://www.amazon.com/You-Are-Expected-Understand-This/dp/0691208484/ref=sr_1_1?crid=2N77VKKLTOA04&keywords=You+Are+Not+Expected+to+Understand+This&qid=1668749348&sprefix=you+are+not+expected+to+understand+this%2Caps%2C157&sr=8-1). The article said that: "Every computer science teacher should get a copy to show to their students". Since it's okay if I don't understand it, I might try reading it, I suppose.

**Closed as completed** 2022-11-18 03:56 UTC
Labels: bug

**Comment by ghost** [comment] 2022-11-22 04:58
I think this [S.O.](https://stackoverflow.com/questions/73055357/r-4-2-really-messing-up-accented-latin-characters) question refers to the same problem. And [this one](https://stackoverflow.com/questions/73699281/utf8-encoding-with-czech-characters) too. Here's [another one](https://stackoverflow.com/questions/72095576/r-version-4-2-0-and-swedish-letters-%C3%A4-%C3%B6-%C3%A5-not-working-in-newest-r-release-any) that also seems relevant. 

[Another ](https://github.com/rstudio/rstudio/issues/11774)github issue on R-4.2 encoding problems.

**Comment by fraupflaume** [comment] 2022-11-22 17:36
Have you gone this route yet? There's someone specifically for handling R and translation issues for Greek. https://developer.r-project.org/TranslationTeams.html

**Comment by ghost** [comment] 2022-11-22 18:46
Hmm, I think I know him. I see we're also connected on [linkedin](https://www.linkedin.com/in/amarkos). I'll give it a shot.

I've tried to contact [Panagiotis-kanavos ](https://stackoverflow.com/users/134204/panagiotis-kanavos) (He appears in the 2nd link in my previous message, he is also Greek and seems to be experienced enough). I sent him a message and explained my problem (that happened before contacting you), but unfortunately he never replied. (You see, not everyone is like you...)

**Comment by fraupflaume** [comment] 2022-11-22 19:42
I had a whole big message typed out, I thought I was really onto something...but I really wasn't.

However, since you keep providing interesting resources, have you seen or heard of this tool? https://github.com/ksint/pasteLastVal  It's almost better than sliced bread. I was just thinking about how much I missed it while I was using RStudio in my VirtualBox.

**Comment by mink-lge** [comment] 2022-11-30 13:36
Greetings @fraupflaume, (You didn't [hide it](https://github.com/ksint/pasteLastVal/issues/5#issue-1460453375) very well. 😊 
Select the original comment in the "Edited" drop-down box and click "remove revision from history." ) 
Thanks for the tool. Here is what I use to type the special german characters https://github.com/samhocevar/wincompose. 
Oh, about that mailbox. Do you ever go there?
By the way, here is [me watching your SO posts](https://video.twimg.com/ext_tw_video/1597785125370171393/pu/vid/720x754/s4fT25-xPGa_cVqZ.mp4?tag=12).
(When you mark this comment as seen, I will remove it)

**Comment by ghost** [comment] 2023-01-17 16:50
(_I just saw your email, but I haven't had a chance to read it, because I was writing this. Take a look at that._ )
Do you remember [this comment](https://github.com/fraupflaume/rpivotTable/issues/4#issuecomment-1314875054)?
Check out what I found out today !!!!!!! 

It's about the SQL SERVER connection

If instead of `odbc::odbc()` use `RODBCDBI::ODBC()` THERE IS NO PROBLEM.
I suppose you could check it yourself, using this query


```
library(DBI)
# con <- dbConnect(odbc::odbc(), encoding = "CP1253", "ODYSSEUS_PM_64", Uid="sa", Pwd="sqlSQL")
con <- dbConnect(RODBCDBI::ODBC(), dsn="ODYSSEUS_PM_64", user="sa", password="sqlSQL")
# dbDisconnect(con)  

# con <- dbConnect(odbc::odbc(), encoding = "CP1253",  .connection_string = "Driver={ODBC Driver 17 for SQL Server};server=DESKTOP-61HASAC;database=ergose2;Uid=sa;Pwd=sqlSQL;")

dbGetQuery(con, paste("                  
              SELECT  *
              FROM    [ergose2].[dbo].[ACTVCODE]
              WHERE   ([parent_actv_code_id] = 10128 AND [actv_code_id] = 10126)",sep=""))
```
![image](https://user-images.githubusercontent.com/107258922/212959968-11146817-f50b-47e2-a5f7-c49e41164d84.png)

**Comment by ghost** [comment] 2023-01-20 07:30
I have also tried RODBC.  It works too, and provides a parameter to declare db encoding (Moreover, it is continuously and actively updated by its development team). So I tried it with the ASE db. The only problem is in correctly _sending_ queries that include Greek. This seems to be fixed if I replace the dbGetQuery function with a UDF like this. I still need to test if all my reports work ok.

```
My_Get_Query <- function(con, sql_statement) {
   RODBC::sqlQuery(con, iconv(sql_statement, "CP1253", "UTF-8")) #works
 }
```
